#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

# Function to print domain record information
print_domain_record() {
    local record_and_ip
    record_and_ip=$(dig "$2"."$1" +short | tail -1)
    echo "The subdomain $2 is a $(dig "$2"."$1" +short | awk '{print $1}') record and points to $record_and_ip"
}

# Main script
if [[ "$#" == 2 ]]; then
    print_domain_record "$1" "$2"
else
    for sub in "www" "lb-01" "web-01" "web-02"; do
        print_domain_record "$1" "$sub"
    done
fi
